#
# This source file is part of the Plainly iOS project
#
# SPDX-FileCopyrightText: 2025 Stanford University
#
# SPDX-License-Identifier: MIT
#

project: Plainly.xcodeproj
schemes:
- Plainly
report_exclude:
- "**/GeneratedOpenAIClient/OpenAPIGenerator/GeneratedSources/**"
- 'PlainlyShared/**'
