version = 1

[[annotations]]
path = [
    "fastlane/metadata/**",
    "fastlane/screenshots/**",
    "Figures/**",
    "AIHealthLiteracy.xcodeproj/**",
    "AIHealthLiteracy/Resources/**",
    "AIHealthLiteracy/Supporting Files/**",
    "AIHealthLiteracyShared/Sources/AIHealthLiteracyShared/Resources/**",
    "AIHealthLiteracyShared/Tests/AIHealthLiteracySharedTests/Resources/*"
]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
