version = 1

[[annotations]]
path = [
    "fastlane/metadata/**",
    "fastlane/screenshots/**",
    "Figures/**",
    "Plainly.xcodeproj/**",
    "Plainly/Resources/**",
    "Plainly/Supporting Files/**",
    "PlainlyShared/Sources/PlainlyShared/Resources/**",
    "PlainlyShared/Tests/PlainlySharedTests/Resources/*"
]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
