#
# This source file is part of the Plainly iOS project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  app_tests:
    name: Build and Test (App)
    uses: SchmiedmayerLab/.github/.github/workflows/xcodebuild.yml@v0.2
    permissions:
      contents: read
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: Plainly
  shared_spm_pkg_tests:
    name: Build and Test (Shared)
    uses: SchmiedmayerLab/.github/.github/workflows/xcodebuild.yml@v0.2
    permissions:
      contents: read
    with:
      path: PlainlyShared
      runsonlabels: '["macOS", "self-hosted"]'
  firebase_e2e_tests:
    name: Firebase End-to-End UI Test
    uses: SchmiedmayerLab/.github/.github/workflows/xcodebuild-or-fastlane.yml@v0.2
    permissions:
      contents: read
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      setupfirebaseemulator: true
      checkout_submodules: true
      artifactname: Plainly-Firebase-E2E.xcresult
      customcommand: scripts/run-firebase-e2e.sh
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [app_tests, shared_spm_pkg_tests]
    uses: SchmiedmayerLab/.github/.github/workflows/coverage.yml@v0.2
    permissions:
      actions: read
      contents: read
    with:
      coveragereports: Plainly.xcresult PlainlyShared.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
